### PR TITLE
Structured out basic scaffolding & Forms & Routing & React-like File System

### PR DESCRIPTION
**Pull request by JacobMGEvans**
- Added Reach Router which focuses on accessibility
- Added Formik for any forms and added a basic example
- Scaffolded out some basic React-like file structure 
- Didn't add too much since I saw **storybook** added in another PR which is a great tool that should be utilized for building out the **components** 

- Updates to packages

### CODE REVIEW

**Comment by JacobMGEvans** [comment]
I added .babelrc and .eslintrc 
- The babel plugins and packages might be a little redundant because of react-scripts 
however, if needed they can just be removed
- ESlint and Prettier, however, are not redundant and are fantastic powerful tools for coding.

**Comment by JacobMGEvans** [comment]
Resolved Merge Conflicts

**Comment by JacobMGEvans** [comment]
I apparently did not keep this branch updated lol, I fixed more inconsistencies with the base master branch.

**Comment by JacobMGEvans** [comment]
So there is a way to utilize Formik AND the Netlify Forms just a heads up that is a powerful combination.

**Comment by JacobMGEvans** [comment]
@kcloud99 @russtaylor @JWTappert @ctsstc  Not sure who does the reviews... Or if any of this I did interest anyone?

**Comment by russtaylor** [comment]
Hey @JacobMGEvans - I'm not super familiar with everything that you added, but upon looking it up, I think it all makes sense. So I'm good with the changes. I don't know if someone else wants to weigh in - if no one does in the next day or so, I'll get this merged in.

**Comment by JacobMGEvans** [comment]
@russtaylor I am more than happy to also discuss any of it. 😁

**Comment by JacobMGEvans** [comment]
I started prototyping out some calendar with material ui picker 🙂

**Comment by JacobMGEvans** [comment]
Hey, @russtaylor just wanted to check if you have any questions or things you'd like to discuss the technologies.  😁

**Comment by russtaylor** [comment]
I was just bein' slow! But this lgtm overall. :-)

**Comment by JacobMGEvans** [comment]
Awesome! 🤩 also sidenote I lived in La Pine when I was in middle school
😆😂

**Pull request merged**
